### ISSUE TITLE
Rifrasare "propagazione"

### ISSUE THREAD

**Issue by mellowiz** [carmelo0x99/Corso-di-fotografia#1]

**Comment by mellowiz** [comment]
Da: Studio della propagazione della luce assimilata a raggi rettilinei (propagazione)
A: **Propagazione**: la luce si propaga sostanzialmente in linea retta (raggi)

**Comment by carmelo0x63** [comment]
diff --git a/corso-foto.md b/corso-foto.md
index f5f240c..030a97c 100644
--- a/corso-foto.md
+++ b/corso-foto.md
@@ -21,7 +21,7 @@ Carmelo Califano per ELIS - Smart Alliance
 ## Parte I - Tecnica
 
 ### Ottica geometrica
-- Studio della propagazione della luce assimilata a raggi rettilinei (**propagazione**)
+- **Propagazione**: la luce si propaga sostanzialmente in linea retta (raggi di luce)
 - **Riflessione**: il raggio di luce incidente "rimbalza" con lo stesso angolo con cui incide sulla superficie
 - **Rifrazione**: il raggio di luce che attraversa una discontinuità viene deviato in maniera prevedibile (**indice di rifrazione**)
